version: "3.8"

services:
  client:
    build:
      context: ./client
    image: duc/rtc_client
    container_name: rtc_client
    ports:
      - 5173:5173
    volumes:
      - ./client:/app
      - ./client/.env:/app/.env
