version: "3.8"

services:
  client:
    build:
      context: ../client
    image: duc/rtc_client_prod
    container_name: rtc_client_prod
    ports:
      - 4200:4200
  server:
    build:
      context: ../server
    container_name: rtc_server_prod
    image: duc/rtc_server_prod
    expose:
      - 5000
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: mysql
    container_name: rtc_db_prod
    expose:
      - 3306
    volumes:
      - ./db/data:/var/lib/mysql
      # - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=abc
      - MYSQL_DATABASE=rtc_db
  bot:
    build:
      context: ../bot
      dockerfile: ./Dockerfile
    image: duc/rtc_bot_prod
    container_name: rtc_bot_prod
    # volumes:
    #   - ./bot:/app
    ports:
      - 5005:5005
    expose:
      - 5005
    depends_on:
      - db
  nginx:
    build:
      context: ../nginx
    container_name: rtc_nginx_prod
    image: duc/rtc_nginx_prod
    ports:
      - 80:80
    depends_on:
      - server
      - client
