version: "3.8"

services:
  client:
    build:
      context: ../client
    image: duc/rtc_client_prod
    container_name: rtc_client_prod
    # ports:
    #   - 5173:5173
    # volumes:
    #   - ./client:/app
    #   - ./client/.env:/app/.env
  server:
    build:
      context: ../server
    container_name: rtc_server_prod
    image: duc/rtc_server_prod
    expose:
      - 5000
    # ports:
    #   - 5000:5000
    # volumes:
    #   - ./server:/app
    #   - ./server/.env:/app/.env
    depends_on:
      - db
  db:
    image: mysql
    container_name: rtc_db_prod
    # ports:
    #   - 33065:3306
    expose:
      - 3306
    volumes:
      - ./db/data:/var/lib/mysql
      # - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=abc
      - MYSQL_DATABASE=rtc_db
  # bot:
  #   build:
  #     context: ../bot
  #     dockerfile: ./Dockerfile
  #   image: duc/rtc_bot_prod
  #   container_name: rtc_bot_prod
  #   ports:
  #     - 5005:5005
  #   expose:
  #     - 5005
  #   volumes:
  #     - ./bot:/app
  #   depends_on:
  #     - db
  nginx:
    build:
      context: ../nginx
    container_name: rtc_nginx_prod
    image: duc/rtc_nginx_prod
    ports:
      - 3080:80
    volumes:
      - ../client/dist:/usr/share/nginx/html
    depends_on:
      - server
      - client
